<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function music_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.music_search':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Here is all the information you need about the Music Search module.') . '</p>';
      return $output;
    default:
  }
}
